### ISSUE TITLE
Refile is removing animation from gifs

### ISSUE THREAD

**Issue by lazaronixon** [elabs/refile#102]
if provide additional metadata file is showed as a gif but without animation.

**Comment by jnicklas** [comment]
I think CarrierWave supports rescaled GIFs, but it's very, very slow. I'm not actually sure if doing this is a good idea, it can be a performance bottleneck.

**Comment by lazaronixon** [comment]
But it was working before, without extension... i think the problem is format method.. maybe some fix to dont convert gif to gif can solve the problem

**Comment by jnicklas** [comment]
Hmm, strange. It's weird that MiniMagick even does anything if the format is already correct. I'd appreciate a PR for this if you have the time!

**Comment by lazaronixon** [comment]
#104
