### ISSUE TITLE
Update record with file is lauching validation

### ISSUE THREAD

**Issue by lazaronixon** [elabs/refile#103]
Not is possible update a record with file on version 0.5.0.
When I try to do that is lauched a invalid_content_type validation.

**Comment by jnicklas** [comment]
I was unable to replicate this. Could you describe step by step exactly what you're doing to get this error, or even better write a failing feature test (`spec/refile/features`).

**Comment by lazaronixon** [comment]
Solved here... It happens when content_type collumn is not created. It is really necessary?

**Comment by jnicklas** [comment]
Hmm, works fine for me even when storing just the `id` column. If you could try to write a failing spec that'd help a lot.

**Comment by lazaronixon** [comment]
#107

**Comment by jnicklas** [comment]
Weird, no idea why it worked when I tried it before. I took some of #107 but didn't pull the whole thing in because I was unsure of the copyright status of the image in the PR. I used a photo I've taken myself instead, just to be sure. The fix was relatively simple.

**Comment by jnicklas** [comment]
Try it now and see if it works for you!

**Comment by IanJBriggs** [comment]
Hmm I am still getting validation on the model when updating. It works great when I have an image using the :image validation. But when I go to save the model a second time there isn't an image in the file field, and therefore seems to spark the validation. To make it work, I have to select the image again before save.
