### ISSUE TITLE
Using presigned exposes AWS key to DOM

### ISSUE THREAD

**Issue by IanJBriggs** [elabs/refile#105]
When setting an attachment helper for direct as true it exposes the AWS key as a data attribute on the input field. 

E.g.  data-fields="{"AWSAccessKeyId":"xxxxxxx"....

Could we not use the events and send the file to a middle man controller that grabs the AWS details server side and then upload it to cache? 

Is this a big hit to security doing this? I know there are lots of BOTs scraping for these keys...

**Comment by jnicklas** [comment]
This is the way that Amazon themselves suggests to do this. The AccessKeyId is not secret, it's the SecretAccessKey which is the secret part. We'll probably move to making an AJAX request to fetch the presign data at some point, but it'll be to support multiple file uploads. I don't think this is a security concern.

**Comment by IanJBriggs** [comment]
Ah! thanks for clearing that up.

**Comment by IanJBriggs** [comment]
For some reason when I enable pre-signed the attachment id isn't stored after update. When I remove pre-signed it saves fine. Any reason why that might be?

**Comment by jnicklas** [comment]
@IanJBriggs works just fine for me, can you describe in more detail exactly what it is you're doing?

**Comment by jnicklas** [comment]
@IanJBriggs please open a separate issue for this problem if it persists.
