### ISSUE TITLE
Mongoid Support

### ISSUE THREAD

**Issue by everaldo** [elabs/refile#108]
Hello! I would like to know if Refile already support Mongoid out of the box.

Thanks!

**Comment by jnicklas** [comment]
No, it does not. I think mongoid support would be best served by an external gem. It shouldn't be hard to make this work. The [ActiveRecord integration](https://github.com/elabs/refile/blob/master/lib/refile/attachment/active_record.rb) is very simple.

**Comment by everaldo** [comment]
Thank you very much!

**Comment by jturolla** [comment]
Any gem?

**Comment by DimaSamodurov** [comment]
Try this https://github.com/DimaSamodurov/refile-mongoid . It's an early version, you'll need to refer github in Gemfile.
