### ISSUE TITLE
The two form fields have the same id

### ISSUE THREAD

**Issue by jensljungblad** [elabs/refile#112]
Seems this was a recent change. The `cache_id` field was renamed so that now it has the same id as the file input field. This caused some problems for us, because we have a label element for the file field. Now the label matches the hidden field instead. 

I guess the order of the fields could be swapped to solve our scenario, but unless there's a particular reason the two elements share the same id, perhaps one could be renamed. An id is only supposed to occur once per page anyways.

**Comment by jnicklas** [comment]
Yeah, the hidden field should not have an `id`. This is a bug.

**Comment by jnicklas** [comment]
Fixed :)

**Comment by jensljungblad** [comment]
Thanks :) Will you release a new version soon?

**Comment by jnicklas** [comment]
Just pushed a new version. Let me know how it works out for you. The 0.5 series has been a bit buggy, unfortunately, hopefully we'll get it all sorted soon.

**Comment by jensljungblad** [comment]
Will keep an eye out. Thanks!
