### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by arrowcircle** [elabs/refile#116]
Hi! Are you planning to add ability to run it as a separate application? It would be cool to have suck app as a separate static storage

**Comment by jnicklas** [comment]
This should already be possible, it's just not documented.

**Comment by arrowcircle** [comment]
Is it divided to client(rails) and server(refile) parts?

**Comment by jnicklas** [comment]
You have to have the gem installed in both, but you can run the Rack app on its own by running it from a Rackup file.

**Comment by arrowcircle** [comment]
How I can tell refile client to use refile server?

**Comment by darkleaf** [comment]
@arrowcircle, see that:
https://github.com/refile/refile/blob/master/lib%2Frefile%2Frails%2Fattachment_helper.rb#L75
https://github.com/refile/refile/blob/master/lib%2Frefile.rb#L277

**Comment by abitdodgy** [comment]
Has anyone been able to run Refile on a separate server, and if so, would be you kind enough to share how you did it?

**Comment by darkleaf** [comment]
I don't do this.

I think you need:
1.  thin server, because it use event machine(non block IO)
2. Mount refile sinatra app in separate rackup file(which used by thin server)
3. Use direct upload
4. Configure refile helpers
