### ISSUE TITLE
ArgumentError (does not respond to `eof?`.)

### ISSUE THREAD

**Issue by danieldocki** [elabs/refile#117]
appears that when sending the image.

```
ArgumentError (does not respond to `eof?`.):
  app/controllers/managers/products_controller.rb:49:in `block in update'
  app/controllers/managers/products_controller.rb:48:in `update'
```

any suggestions?

**Comment by jnicklas** [comment]
We need some more info on this one. What does your code look like, what did you do?

**Comment by jnicklas** [comment]
See https://github.com/elabs/refile/blob/master/CONTRIBUTING.md

**Comment by danieldocki** [comment]
Sorry @jnicklas 

This is my form, when I sent
```
<%= simple_form_for([@establishment, @category, @product]) do |f| %>
  <%= f.error_notification %>

   <%= f.input :name %>
   <%= f.input :description %>
   <%= f.input :price, as: :currency %>
   <%= f.attachment_field :image %>

    <%= f.button :submit, data: { disable_with: t('waiting') } %>
<% end %>
```

I get this error

```
ArgumentError (does not respond to `eof?`.):
  app/controllers/managers/products_controller.rb:49:in `block in update'
  app/controllers/managers/products_controller.rb:48:in `update'
```

product.rb
```
class Product < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include PgSearch
  attachment :image
```

where I am going wrong?

**Comment by jnicklas** [comment]
That's a rather old version of Rails. Could well be that it doesn't have `eof?`. I actually think we're not using `eof?` anymore since we refactored to use `copy_stream`, so we can probably remove that from the required interface.

**Comment by jnicklas** [comment]
Just pushed a commit which removes the requirement of responding to `eof?`. Can you upgrade to master and see if it fixes your problems?

**Comment by danieldocki** [comment]
@jnicklas 

Error about "close"

```
ArgumentError (does not respond to `close`.):
  app/controllers/managers/products_controller.rb:49:in `block in update'
  app/controllers/managers/products_controller.rb:48:in `update'
```

**Comment by jnicklas** [comment]
So this is `UploadedFile` in Rails 3.2: https://github.com/rails/rails/blob/3-2-stable/actionpack/lib/action_dispatch/http/upload.rb

And in 4.0: https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_dispatch/http/upload.rb

Seems like it incurred quite a big change from 3.2 to 4.0 to make it more IO like.

It seems to me that the `IO.copy_stream` refactor has removed the need for `uploadable.close` as well. We probably want to leave closing the uploadable object to the caller anyway. And Rails is going to do that for us anyway when the request finishes.

**Comment by jnicklas** [comment]
Ugh so apparently removing `close` and `eof?` from the interface causes problems for other backends. I think the most sensible thing would be for Refile to monkeypatch in those methods if they don't exist on Rails 3. I'll cook up a patch for this soon.

**Comment by jnicklas** [comment]
Monkeypatches added, please take a look at the latest master and see if it works for you.

**Comment by danieldocki** [comment]
@jnicklas 

You are awesome, is working. Thanks :)

**Comment by eddiefisher** [comment]
not working for me
```
Using rails 3.2.19
Using refile 0.5.3
```
```
does not respond to `eof?`.
Rails.root: /Users/eddifisher/sites/anjlab/planet

Application Trace | Framework Trace | Full Trace
refile (0.5.3) lib/refile/backend_macros.rb:25:in `block (3 levels) in verify_uploadable'
refile (0.5.3) lib/refile/backend_macros.rb:23:in `each'
refile (0.5.3) lib/refile/backend_macros.rb:23:in `block (2 levels) in verify_uploadable'
refile (0.5.3) lib/refile/attacher.rb:91:in `cache!'
refile (0.5.3) lib/refile/attacher.rb:74:in `set'
refile (0.5.3) lib/refile/attachment.rb:58:in `block (2 levels) in attachment'
```

**Comment by eddiefisher** [comment]
https://gist.github.com/eddiefisher/779efe5c85f224da69cf code

**Comment by danieldocki** [comment]
@eddiefisher  use direct from repository

```
gem 'refile', require: ['refile/rails', 'refile/image_processing'], git: 'https://github.com/elabs/refile.git'
```

**Comment by eddiefisher** [comment]
tnx ))) it's worked for me )
