### ISSUE TITLE
getting exif data from images

### ISSUE THREAD

**Issue by ultramaroon** [elabs/refile#121]
I am attempting to pull exif data from uploaded images (specifically latitude/longitude but shouldn't matter), and I can't figure out how to access the file after it has been uploaded. I'm using mini_exiftool, and trying to do put something like this in an after_save hook on the model: 
exif_data = MiniExiftool.new(self.image) or exif_data = MiniExiftool.new(self.image.download) or exif_data = MiniExiftool.new(self.image.to_io), all of which fail. Perhaps I need the path to the file, but I am unable to figure that out using the documentation. Or perhaps there is an easier way to do this. Any help is appreciated.

**Comment by jnicklas** [comment]
Seems like MiniExiftool expects a local path, so it'd probably be easiest to do `image.download.path`.

**Comment by jnicklas** [comment]
The reason you can't just get the path is because the File may not be stored on the local filesystem, and even if it were, you probably don't want to hand out its path, because someone might end up modifying the stored file.

**Comment by ultramaroon** [comment]
Thanks for the quick reply, Jonas. The download.path method was exactly what I was looking for! I poked around trying to find it but just didn't get there.

This is a somewhat different question (and probably doesn't belong in this issue, but maybe in a wiki or blog post instead) but hopefully you might give your thoughts. I've used Carrierwave before (and paperclip, to a lesser degree; they are more similar to each other than either are to Refile), and I wonder if there is a use case that you think one paradigm works better than the rest. For example, I understand the advantage of processing on the fly (hopefully once, and then using a CDN), but what are the disadvantages? Cost, perhaps, if you are doing a photo sharing site and have a very large number of photos? (or maybe not, I don't know CDNs much). Is there a case when you would prefer the way Carrierwave does things or do you think you'd pretty much use Refile (if not currently, then in its "finished" "ideal" state) for all use cases? Is this, for example, how you think Facebook does its image storage?

I read through your blog post and the readme, but am still trying  to get a better feel for pros and cons.

Oh, and maybe this is because I am just doing it all in development on a local machine, but when the photos show up on the page, there's no way to right-click and view just that image or save that image to file; it automatically downloads a file that's the name of the attachment. (I understand that the image is being served up in the sinatra app; but is there any way around the fact that all the files have the same name/lack file extensions/etc.)

Thanks again, Jonas.

**Comment by jnicklas** [comment]
With the way we've currently set up Refile, you definitely get more control over authorization with CarrierWave. You also never get that first request hitting your app. If you have files which are rarely downloaded, then that might be better.

I would imagine that Facebook has a dedicated pipeline for images, where they are received and then processed asynchronously, so they are probably already scaled when you ask for them. So it's more akin to what someone would build with a sophisticated CarrierWave setup, where they create background jobs to scale the images as soon as they're uploaded. They probably have dedicated machines for this and they can make use of CPU extensions and GPUs to do the image processing.

Refile is simple. It's purposefully simple. If you have very sophisticated needs, it probably will be too simple. But I find that for a lot of applications, I just need to upload some files and be done with it, and have it not be painfully slow. That's where Refile's sweetspot sits, IMO.

As for your second question, check the issues, this has been discussed before.
