### ISSUE TITLE
S3 permissions and authenticated reads

### ISSUE THREAD

**Issue by holden** [elabs/refile#122]
Hi,

Refile looks great, I'm wondering how I can replicate functionality similar to Carrierwave for setting permissions on uploaded files and if there's a way to use s3 authenticated urls to gain access to them.

Carrierwave has the authenticated_url method and the ability to set an uploader to private, etc.

```
def fog_public
  false
end
```

http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave/Storage/Fog/File:authenticated_url

Any pointers would be appreciated, thanks.

**Comment by jnicklas** [comment]
So, Refile takes a fundamentally different approach on this. File are always private, never public, and Refile always streams them through the app, it does not generate URLs to the stored files. This might seem a bit insane at first glance, but it's actually much better. If you're using a CDN, only the initial request hits your application.

If you want even more control over authentication and authorization, the best way is to actually create your own controller-endpoint which serves the files. You could also use CloudFront authenticated URLs and make sure to hide your backend from anyone that's not CloudFront.

It would actually be possible for us to serve even that first request directly from S3 if the file does not require processing, but at the expense of worse cache performance, so we've so far decided against it (See #1).

**Comment by mikelieser** [comment]
Hi @holden 

i made some tweaks regarding authenticated aws urls in my fork. have a look at this commit.

https://github.com/mikelieser/refile/commit/eff658ffaad471479d43223ba578ebe2641b66d0

You can define a lamba function in your refile initializer like so:

```ruby
if ENV["CLOUDFRONT_SIGN_URLS"] == "true"
  AWS::CF::Signer.configure do |config|
    config.key = ENV.fetch('CLOUDFRONT_SIGNER_PK')
    config.key_pair_id = ENV["CLOUDFRONT_SIGNER_KEY_PAIR_ID"]
    config.default_expires = 3 # expires in (minutes)
  end
  
  Refile.url_finalizer = lambda { |uri, object, name| AWS::CF::Signer.sign_url(uri.to_s) }
end
```

https://github.com/58bits/cloudfront-signer

**Comment by felipefontoura** [comment]
Hello @mikelieser,

Do you still have this code? 

https://github.com/mikelieser/refile/commit/eff658ffaad471479d43223ba578ebe2641b66d0

**Comment by mikelieser** [comment]
Hi @felipefontour,

I'm sorry, but this code is no longer on github.

Basically it's just that, in combination with the example usage I already posted.

<img width="1250" alt="url_finalizer" src="https://cloud.githubusercontent.com/assets/372492/16903055/2d01fa48-4c73-11e6-894f-966777bffa59.png">

[refile.rb.txt](https://github.com/refile/refile/files/368132/refile.rb.txt)
