### ISSUE TITLE
attachment_field_image_tag

### ISSUE THREAD

**Issue by stephendolan** [elabs/refile#123]
Hi, love this gem and can't wait to see it mature.

Just wanted to make sure I'm not missing a helper that would allow us to click on the current image to submit a new one?

**Comment by walterdavis** [comment]
I usually create a label for this purpose:

	<label for="my_file_field">
		<img src="path/to/thumbnail" />
	</label>
	<input name="my_file_field" ... >

Clicking a label is exactly like clicking the file input, so you should be all set.

Walter

**Comment by jnicklas** [comment]
See also #20, which is somewhat related. I agree with @walterdavis, labels are the easiest way of achieving this.

**Comment by stephendolan** [comment]
Just what I was looking for. Thanks, guys!
