### ISSUE TITLE
Independent Upload

### ISSUE THREAD

**Issue by Austio** [elabs/refile#127]
Hey All,

Just checked through the code for a while.  Is there any way for an indepenedent applicaiton that is not in rails to hit the mounted sinatra app and then upload a file.

For instance, a mobile app that is needing to upload images.

**Comment by jnicklas** [comment]
All you need to do is generate the right URL. The Refile app can receive file uploads. Check here: https://github.com/elabs/refile/blob/master/lib/refile/app.rb#L59-L65
