### ISSUE TITLE
integrate refile with bootstrap3-wysihtml5

### ISSUE THREAD

**Issue by mabed** [elabs/refile#131]
What would be involved in trying to get refile upload to work with something like this editor?

bootstrap3-wysihtml5-bower forked from hockic/bootstrap-wysihtml5

**Comment by jnicklas** [comment]
Programming probably. ;)

**Comment by mabed** [comment]
Right on :) I wouldn't mind learning & researching, some pointers to put me on the right direction would be super helpful. I can't get my head around how to connect the JavaScript to RoR.

**Comment by jnicklas** [comment]
I'm afraid I know nothing about that library, and I can't really help you with how to integrate with it. Making requests to Rails from JS should be covered by a lot of resources online. I have no idea how this ties in with Refile, so can't really help you with that. Sorry. You could try asking on StackOverflow.
