### ISSUE TITLE
Does Refile support Polymorphic Relationships

### ISSUE THREAD

**Issue by phyxavier** [elabs/refile#132]
So I have this current code that is great for uploading several images, however, the form breaks as shown here with multiple images displaying and well as multiple upload buttons: https://www.evernote.com/shard/s475/sh/b2ae3739-1419-41de-bacc-757b4da43b1c/5cd07c4d7a9994220c1449b76174ac2d

I am only trying to display the lastest image only. Thanks

     ._20.add_left_margin.image_mobile_optimization
        = f.fields_for :assets do |ff|
          .w-clearfix.header_div
            %h3 Add Assets
          .image_-_label_div
            .squeare_image=@collection.assets.present? ? attachment_image_tag(@collection.assets.last, :asset_image, :fill, 208, 208, fallback: "image-placeholder.svg", class: 'pic') : image_tag('image-placeholder.svg', class: 'pic')
          .attachment_text= ff.attachment_field :asset_image

**Comment by jnicklas** [comment]
Not sure what is going wrong here. Refile wouldn't cause buttons to show up multiple times, so I don't think this has something to do with Refile.
