### ISSUE TITLE
Unable to change existing file

### ISSUE THREAD

**Issue by hellojere** [elabs/refile#134]
Refile works flawlessly except I'm unable to change the file for an existing record. It's failing on normal and direct upload in both development and production environment with the latter using Amazon S3. 

Log reveals the correct parameters being sent in the update request and they should be white listed correctly in the controller, as the original upload works. 

Also the Javascript callbacks are returning the correct image when using the direct upload, but the original file I'm trying to replace just keeps on coming back after saving the whole form. Also the correct parameters seem to be added to the hidden field. 

Anyone else experiencing this? 

Gemfile.lock:     
>
    refile (0.5.3)
      mime-types
      sinatra (~> 1.4.5)

**Comment by jnicklas** [comment]
Not really sure how to help you on this one. White listing is the most likely culprit, IMO. Make *sure* that's not the problem.

**Comment by hellojere** [comment]
Am trying through polymorphic association. Created a dummy app and works, so must be somewhere there. Sorry for bothering.
