### ISSUE TITLE
nginx cache problem

### ISSUE THREAD

**Issue by d4be4st** [elabs/refile#136]
This line is messing with my nginx setup:

https://github.com/elabs/refile/blob/master/lib/refile.rb#L246

I get cache url   /attachments/cache/fill/200/200/c90e25efa8d351f9d52cf6bfc4504add6839dad4b5500852118f1bed77a3/6.png 
and nginx thinks this is an asset and wont go through rails/refile but will return 404 instantly.

If i comment that line, everything works fine

**Comment by jnicklas** [comment]
Can't you just change your nginx config? What am I missing here?

**Comment by d4be4st** [comment]
I would be very helpful if someone helps me with this.
I do not know how would i even google this problem.

**Comment by jnicklas** [comment]
nginx is serving your PNG files as static files. You want to tell it to not do that. Somewhere in your config, you're telling nginx to do this, and you'll want to switch it off. If you don't understand what your nginx config is doing then you really need to RTFM. Don't just copy config without understanding what it's doing.

Read this: http://nginx.org/en/docs/beginners_guide.html

Then this: http://guides.rubyonrails.org/asset_pipeline.html#in-production

And this: http://dennisreimann.de/blog/configuring-nginx-for-the-asset-pipeline/

**Comment by d4be4st** [comment]
I do not want to turn off serving all your static files with nginx. Because refile attachment_url is not a static file, it is a path to Refile:App which then servers you a static file.
It has nothing to do with assets pipelines even.

**Comment by jnicklas** [comment]
I linked you to the examples because they tell you how to only serve assets at a specifc path prefix as static files. This way you can serve stuff from the asset pipeline as static files, while serving the files from Refile via the Backend. I cannot write the nginx configuration for you. I linked the relevant docs, and relevant examples on how to set this up properly.

**Comment by d4be4st** [comment]
Ok Thanks

**Comment by d4be4st** [comment]
For future references you need to add this to your nginx server conf:

    	location ~ ^\/attachments\/.*\.(png|jpg|jpeg|gif) {
		passenger_enabled on;
	}
