### ISSUE TITLE
Saving the original image and a thumbnail

### ISSUE THREAD

**Issue by anylyne** [elabs/refile#143]
I would like to upload a image, store the original image and a small version of it. Is there a way to do this?

**Comment by geetfun** [comment]
I think the library's design is to *not* store thumbnails. 

The original image is handled by the Refile's attacher, but any thumbnails would generated dynamically and cached via a CDN, such as Cloudflare. In production, it would be essential to have a CDN *in front* of your app servers.

**Comment by thomasklemm** [comment]
@anylyne That's the way `carrierwave` handles processing, e.g. generating thumnails when an image is uploaded. `refile` though is designed differently, generating thumbnails or in general [processing attachments on demand](https://github.com/elabs/refile#processing). As @geetfun says, you'd set up a CDN in production to cache the processed results, see [this Readme section](https://github.com/elabs/refile#3-rack-application). This means that the first time an image version like a thumbnail is requested, the app processes the request and generates the thumbnail on the fly, while every following request is served by the CDN, so future requests will never hit your app.

**Comment by anylyne** [comment]
Thank you, guys! I'll figure it out. ;)

**Comment by lichtamberg** [comment]
So this gem is not really usefull when I want to store sensitive data, like passport images? I dont want to distribute such images via CDN?

Is there no way to store thumbnails with refile itself?

**Comment by jnicklas** [comment]
@lichtamberg you can always run your own HTTP cache. Rack-Cache is the simplest solution, but something like Varnish is obviously way more performant. If that doesn't work for you, then you should probably look into using CarrierWave instead.
