### ISSUE TITLE
Support upload/process/play videos

### ISSUE THREAD

**Issue by lazaronixon** [elabs/refile#148]
I know this is a ambitious feature, but I think refile was also.. Would be great refile provide a way to upload/process/play videos using same principles of image upload.. Instead "Minimagick" use [streamio-ffmpeg](https://github.com/streamio/streamio-ffmpeg) and provide a helper to play it, maybe using [clappr](https://github.com/clappr/clappr).

**Comment by activestylus** [comment]
This is very ambitious, and probably outside the scope of an already impressive gem. That said I have just this exact need. Would make an excellent gem to accompany refile

**Comment by geetfun** [comment]
+1 Can definitely see use cases for this.

Currently Refile uses a Sinatra app to *stream* the files. Perhaps if the file is a video, a different Sinatra endpoint could be used to transcode and stream?

**Comment by jnicklas** [comment]
I would prefer for this kind of thing to be handled by separate gems. The image processing is going to be split out into a separate gem too.
