### ISSUE TITLE
Question: Copying images around?

### ISSUE THREAD

**Issue by brightbits** [elabs/refile#156]
With CarrierWave, we had problems when trying to copy the information about a stored image to another model. It would try and download, reprocess and upload the image again separately. Is this still something that would happen? I'm uncomfortable with the magic of setting an attribute on my model and lots of stuff happening without me thinking about it first, as they are costly operations when it comes down to it.

Thanks

**Comment by jnicklas** [comment]
Probably the most fundamental design mistake I made in CarrierWave is that the mounted column has the same name as the DB column underneath. This is not the case in Refile. Refile does nothing magic with DB columns at all. So if you set `profile_image_id` in your model, nothing magic happens, Refile isn't even involved at all.

**Comment by jnicklas** [comment]
Does that answer your question sufficiently?

**Comment by brightbits** [comment]
It does indeed, I look forward to using it some point in the future! :) Thank you for your work

**Comment by jnicklas** [comment]
There are ways around this in CarrierWave too, btw. You can always use Rails' `write_attribute` for example. That's what CarrierWave uses internally.

**Comment by brightbits** [comment]
Yeah, I ended up using `new_model.update_attribute(avatar: old_model.attributes["avatar"])` or something similar :)
