### ISSUE TITLE
s3 url

### ISSUE THREAD

**Issue by xn** [elabs/refile#87]
Reading through your README and through the code, I don't see how I would get the s3 url for an attachment outside of a view. I've successfully uploaded it and played around with the file object in the console.

I see this: https://github.com/elabs/refile/blob/3ae48212077d1aba496899ac7ae4e4a43acc6352/lib/refile/rails/attachment_helper.rb#L40

But that doesn't seem to help me outside of a view.

What am I missing?
Thanks,
-xn

**Comment by jnicklas** [comment]
1765ef09beef2d32d748bad5f790b60d85d6eb18
