### ISSUE TITLE
File type validations should support direct uploads

### ISSUE THREAD

**Issue by lazaronixon** [elabs/refile#98]
Validations works well when I use
```ruby
<%= form.attachment_field :profile_image %>
```
but with 
```ruby
<%= form.attachment_field :profile_image, direct: true, presigned: true %>
```
validation not is performed, I know to validate before send to S3(cache) is more a javascript work, but would be nice validate before send to store.

**Comment by jnicklas** [comment]
I'm working on that! See #81. This actually turns out to be incredibly tricky to implement without turning the code into a complete mess :(

**Comment by voytee** [comment]
It doesn't validate my file when uploading using ```direct: true```

In my model I have:

``` attachment :avatar, type: :image```

and in the form:

```= form.attachment_field :avatar, direct: true```

In chrome and safari the browser does not allow to select non image files (accept html attribute set correctly) but in Firefox I can upload for example a PDF as an Image

Any help, appreciated,

Thanks
